name: digni_scanner
description: DIGNI SCANNER by DIGNI - MCL
publish_to: "none"
version: 1.1.5+115

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.4.2
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  audioplayers: ^6.5.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/sounds/check.wav
    - assets/sounds/approved.wav

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/brand/icono-digni.png"
  min_sdk_android: 23
