name: digni_scanner
description: DIGNI Scanner V3 native preview (not connected to production)
publish_to: "none"
version: 3.0.0-preview.1+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.4.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
